version: '3'
services:
  medicContDB:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
